### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by nicinabox** [jt2k/nodevember-schedule#1]
I used this all day at the conference. It was super helpful to compare simultaneous talks! 

I was wondering if you'd be willing to add local storage support for checked item? It's kind of a bummer to lose all the state with an accidental refresh. 

I could also send a PR later if you like as well.

**Comment by jt2k** [comment]
There is local storage support, but there definitely could be some bugs.  I put this together pretty quickly.  If you can find the problem, feel free to submit a PR.

**Comment by jt2k** [comment]
Closing this issue since:
1. I haven't been able to reproduce the local storage problem
2. Nodevember 2015 is over
3. @nicinabox has created this: https://github.com/nicinabox/nodevember-schedule
